force-app/main/default/objects/Contact/fields/EmailVerificationDateTime__c.field-meta.xml
<CustomField>
    <fullName>EmailVerificationDateTime__c</fullName>
    <description>This field captures the date time when the email was verified by HCP</description>
    <label>Email Verification Date time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EmailVerificationKey__c.field-meta.xml
<CustomField>
    <fullName>EmailVerificationKey__c</fullName>
    <description>This field contains the email verification key shared to customer</description>
    <label>Email Verification Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsEmailVerified__c.field-meta.xml
<CustomField>
    <fullName>IsEmailVerified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Email Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/VerificationLinkExpiryDateTime__c.field-meta.xml
<CustomField>
    <fullName>VerificationLinkExpiryDateTime__c</fullName>
    <description>This field tracks the date and time when the verification link will expire</description>
    <label>Verification link Expiry Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/EmailVerificationController.cls
public without sharing class EmailVerificationController {
    
    // Returning errorCode if proper contact found '0' else '1'
     @AuraEnabled
     Public static Integer updateContactRecord(String emailVerificationKey){
        Integer errorCode;
        //to get contact for verification based on key
        try{
        List<Contact> contacts = [
            SELECT 
                Id,
                EmailVerificationKey__c,
                VerificationLinkExpiryDateTime__c,
                isEmailVerified__c
            FROM Contact 
            WHERE EmailVerificationKey__c=:emailVerificationKey 
AND EmailVerificationKey__c != NULL
            LIMIT 1];
        if(contacts.isEmpty()){
            return errorCode = 1;
        }else{
            Contact con = contacts[0];
            if(con.VerificationLinkExpiryDateTime__c >= System.now() && !con.isEmailVerified__c){ 
                con.isEmailVerified__c = true;
                con.EmailVerificationDatetime__c = System.now();
                update con;
                return errorCode =  0;
           }else  {
                return errorCode = 1;
           }
        }
        }catch (Exception e) {
            return errorCode = 1;
        }
    }

}